# name: Test Astarte example
# on:
#   pull_request:
#   push:
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - id: setup-astarte
#       uses: astarte-platform/setup-astarte-action@v1
#       with:
#         realm: test
#         device-id: B552uoZ5SmGQq8d6NhtzPQ
#         register-device: true
#     - name: Use setup-astarte outputs
#       run: |
#         # Here you can use setup-astarte-action outputs
#         echo Realm ${{ steps.setup-astarte.outputs.realm }}
#         echo Device ID ${{ steps.setup-astarte.outputs.device-id }}
#         echo Credentials Secret ${{ steps.setup-astarte.outputs.credentials-secret }}
#         echo Pairing URL ${{ steps.setup-astarte.outputs.pairing-base-url }}
#         echo Pairing JWT ${{ steps.setup-astarte.outputs.pairing-jwt }}
#         echo AppEngine URL ${{ steps.setup-astarte.outputs.appengine-base-url }}
#         echo AppEngine JWT ${{ steps.setup-astarte.outputs.appengine-jwt }}
#       shell: bash