name: Test Called

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  # Allow this workflow to be called  by others
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "check is USELESS_SECRET exists"
        env: 
          super_secret: ${{ secrets.USELESS_SECRET }}
        if: ${{ env.super_secret == '' }}
        run: echo "the secret \'USELESS_SECRET\' does not exist"
