name: Test Called

on:
  push:
    branches:
    - 'main'
    - 'release-*'
  # Allow this workflow to be called  by others
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo a value from a secret
      run: |
        echo "Called workflow says ${{ secrets.USELESS_SECRET }}"
      shell: bash
