name: Test calling

on:
  push:
    branches:
    - 'main'
    - 'release-*'

jobs:
  called-workflow:
    uses: ./.github/workflows/test-called.yaml
    secrets: inherit


  calling:
    name: Call another workflow
    runs-on: ubuntu-latest
    needs:
    - called-workflow
    steps:
      - name: Big step for mankind
        run: echo "Calling workflow says ${{ secrets.USELESS_SECRET }}"
      - name: Small step for man
        run: echo "End calling workflow"
        shell: bash
